### ISSUE TITLE
Problem with INSERT INTO..SELECT on Oracle

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/SqlRender#99]
The Heracles cohort characterization script has been modified to help optimize performance. This was done by inserting each individual cohort analysis into a temp table and at the end of the script, the results are inserted into a pre-defined table to hold the results. This appears to work well except on Oracle and I'm having trouble isolating the problem.

I've extracted the relevant OHDSI-SQL that is causing the issue when performing the INSERT:

```
{DEFAULT @list_of_analysis_ids = '0,1,2,3,4,5,6,7,8,9,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,200,201,202,203,204,205,206,207,208,209,210,211,220,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,500,501,502,503,504,505,506,509,510,511,512,513,514,515,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,800,801,802,803,804,805,806,807,808,809,810,811,812,813,814,815,819,820,900,901,902,903,904,905,906,907,908,909,910,911,912,913,914,915,916,917,918,919,920,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,1100,1101,1102,1103,1200,1201,1202,1203,1700,1701,1800,1801,1802,1803,1804,1805,1806,1807,1808,1809,1810,1811,1812,1813,1814,1815,1816,1817,1818,1819,1820,1821,1830,1831,1840,1841,1850,1851,1860,1861,1870,1871,1300,1301,1302,1303,1304,1305,1306,1307,1308,1309,1310,1311,1312,1313,1314,1315,1316,1317,1318,1319,1320,2001,2002,2003,2004,2005,2006,2007,2011,2012,2013,2014,2015,2016,2017,2021,2022,2023,2024,2025,2026,2027,2031,2032,3000,3001'}


  insert into @results_schema.heracles_results (cohort_definition_id, analysis_id, stratum_1, stratum_2, stratum_3, stratum_4, count_value) 
  --{ 0  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_0 union all }
  --{ 3000  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_3000 union all }
  --{ 3001  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_3001 union all }
  --{ 1  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1 union all }
  --{ 2  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_2 union all }
  --{ 3  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_3 union all }
  --{ 4  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_4 union all }
  --{ 5  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_5 union all }
  --{ 7  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_7 union all }
  --{ 8  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_8 union all }
  --{ 9  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_9 union all }
  --{ 101  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_101 union all }
  --{ 102  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_102 union all }
  --{ 108  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_108 union all }
  --{ 109  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_109 union all }
  --{ 110  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_110 union all }
  --{ 111  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_111 union all }
  --{ 112  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_112 union all }
  --{ 113  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_113 union all }
  --{ 114  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_114 union all }
  --{ 115  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_115 union all }
  --{ 116  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_116 union all }
  --{ 117  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_117 union all }
  --{ 200  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_200 union all }
  --{ 201  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_201 union all }
  --{ 202  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_202 union all }
  --{ 204  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_204 union all }
  --{ 207  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_207 union all }
  --{ 208  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_208 union all }
  --{ 209  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_209 union all }
  --{ 210  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_210 union all }
  --{ 220  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_220 union all }
  --{ 400  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_400 union all }
  --{ 401  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_401 union all }
  --{ 402  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_402 union all }
  --{ 404  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_404 union all }
  --{ 405  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_405 union all }
  --{ 409  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_409 union all }
  --{ 410  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_410 union all }
  --{ 411  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_411 union all }
  --{ 412  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_412 union all }
  --{ 413  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_413 union all }
  --{ 420  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_420 union all }
  --{ 500  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_500 union all }
  --{ 501  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_501 union all }
  --{ 502  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_502 union all }
  --{ 504  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_504 union all }
  --{ 505  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_505 union all }
  --{ 509  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_509 union all }
  --{ 510  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_510 union all }
  --{ 600  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_600 union all }
  --{ 601  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_601 union all }
  --{ 602  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_602 union all }
  --{ 604  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_604 union all }
  --{ 605  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_605 union all }
  --{ 609  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_609 union all }
  --{ 610  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_610 union all }
  --{ 612  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_612 union all }
  --{ 613  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_613 union all }
  --{ 620  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_620 union all }
  --{ 700  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_700 union all }
  --{ 701  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_701 union all }
  --{ 702  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_702 union all }
  --{ 704  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_704 union all }
  --{ 705  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_705 union all }
  --{ 709  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_709 union all }
  --{ 710  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_710 union all }
  --{ 711  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_711 union all }
  --{ 712  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_712 union all }
  --{ 713  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_713 union all }
  --{ 720  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_720 union all }
  --{ 800  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_800 union all }
  --{ 801  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_801 union all }
  --{ 802  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_802 union all }
  --{ 804  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_804 union all }
  --{ 805  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_805 union all }
  --{ 807  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_807 union all }
  --{ 809  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_809 union all }
  --{ 810  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_810 union all }
  --{ 812  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_812 union all }
  --{ 813  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_813 union all }
  --{ 814  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_814 union all }
  --{ 820  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_820 union all }
  --{ 900  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_900 union all }
  --{ 901  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_901 union all }
  --{ 902  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_902 union all }
  --{ 908  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_908 union all }
  --{ 909  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_909 union all }
  --{ 910  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_910 union all }
  --{ 920  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_920 union all }
  --{ 1000  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1000 union all }
  --{ 1001  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1001 union all }
  --{ 1002  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1002 union all }
  --{ 1004  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1004 union all }
  --{ 1008  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1008 union all }
  --{ 1009  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1009 union all }
  --{ 1010  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1010 union all }
  --{ 1020  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1020 union all }
  --{ 1100  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1100 union all }
  --{ 1101  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1101 union all }
  --{ 1200  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1200 union all }
  --{ 1201  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1201 union all }
  --{ 1300  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1300 union all }
  --{ 1301  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1301 union all }
  --{ 1302  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1302 union all }
  --{ 1304  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1304 union all }
  --{ 1305  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1305 union all }
  --{ 1307  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1307 union all }
  --{ 1309  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1309 union all }
  --{ 1310  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1310 union all }
  --{ 1312  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1312 union all }
  --{ 1313  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1313 union all }
  --{ 1314  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1314 union all }
  --{ 1318  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1318 union all }
  --{ 1320  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1320 union all }
  --{ 1700  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1700 union all }
  --{ 1701  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1701 union all }
  --{ 1800  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1800 union all }
  --{ 1804  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1804 union all }
  --{ 1805  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1805 union all }
  --{ 1806  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1806 union all }
  --{ 1807  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1807 union all }
  --{ 1814  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1814 union all }
  --{ 1815  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1815 union all }
  --{ 1816  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1816 union all }
  --{ 1820  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1820 union all }
  --{ 1821  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1821 union all }
  --{ 1830  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1830 union all }
  --{ 1831  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1831 union all }
  --{ 1840  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1840 union all }
  --{ 1841  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1841 union all }
  --{ 1850  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1850 union all }
  --{ 1851  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1851 union all }
  --{ 1860  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1860 union all }
  --{ 1861  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1861 union all }
  --{ 1870  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1870 union all }
  --{ 1871  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1871 union all }
  --{ 2001  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_2001 union all }
  --{ 2002  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_2002 union all }
  --{ 2003  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_2003 union all }
  --{ 2004  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_2004 union all }
  --{ 2005  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_2005 union all }
  --{ 2006  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_2006 union all }
  --{ 2007  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_2007 union all }
  --{ 2011  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_2011 union all }
  --{ 2012  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_2012 union all }
  --{ 2013  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_2013 union all }
  --{ 2014  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_2014 union all }
  --{ 2015  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_2015 union all }
  --{ 2016  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_2016 union all }
  --{ 2017  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_2017 union all }
  --{ 2021  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_2021 union all }
  --{ 2022  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_2022 union all }
  --{ 2023  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_2023 union all }
  --{ 2024  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_2024 union all }
  --{ 2025  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_2025 union all }
  --{ 2026  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_2026 union all }
  --{ 2027  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_2027 union all }
  --{ 2031  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_2031 union all }
  --{ 2032  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_2032 union all } 
  select -1, -1, '', '', '', '', -1;
  -- this final select handles the union all in the case of whatever conditional query runs last
```

The resulting translated/rendered Oracle SQL has the problem of the 'FROM DUAL' keywords are applied multiple times at the end of the script:

```
  --
  SELECT cohort_definition_id, analysis_id, TO_CHAR(stratum_1 ), TO_CHAR(stratum_2 ), 
  TO_CHAR(stratum_3 ), TO_CHAR(stratum_4 ), count_value
  FROM lihgaqqsresults_2031   UNION all 
  --
  SELECT cohort_definition_id, analysis_id, TO_CHAR(stratum_1 ), TO_CHAR(stratum_2 ), 
  TO_CHAR(stratum_3 ), TO_CHAR(stratum_4 ), count_value
  FROM lihgaqqsresults_2032   UNION all  
  SELECT -1, -1, '', '', '', '', -1               FROM DUAL                FROM DUAL                FROM DUAL                FROM DUAL                FROM DUAL                FROM DUAL                FROM DUAL                FROM DUAL                FROM DUAL                FROM DUAL;
  -- this final select handles the union all in the case of whatever conditional query runs last
```

I isolated this down a bit further by eliminating the SELECT statements to see where the first 'FROM DUAL' is introduced and here is the OHDSI-SQL code:

```
{DEFAULT @list_of_analysis_ids = '0,1,2,3,4,5,6,7,8,9,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,200,201,202,203,204,205,206,207,208,209,210,211,220,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,500,501,502,503,504,505,506,509,510,511,512,513,514,515,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,800,801,802,803,804,805,806,807,808,809,810,811,812,813,814,815,819,820,900,901,902,903,904,905,906,907,908,909,910,911,912,913,914,915,916,917,918,919,920,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,1100,1101,1102,1103,1200,1201,1202,1203,1700,1701,1800,1801,1802,1803,1804,1805,1806,1807,1808,1809,1810,1811,1812,1813,1814,1815,1816,1817,1818,1819,1820,1821,1830,1831,1840,1841,1850,1851,1860,1861,1870,1871,1300,1301,1302,1303,1304,1305,1306,1307,1308,1309,1310,1311,1312,1313,1314,1315,1316,1317,1318,1319,1320,2001,2002,2003,2004,2005,2006,2007,2011,2012,2013,2014,2015,2016,2017,2021,2022,2023,2024,2025,2026,2027,2031,2032,3000,3001'}


  insert into @results_schema.heracles_results (cohort_definition_id, analysis_id, stratum_1, stratum_2, stratum_3, stratum_4, count_value) 
  --{ 0  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_0 union all }
  --{ 3000  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_3000 union all }
  --{ 3001  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_3001 union all }
  --{ 1  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_1 union all }
  --{ 2  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_2 union all }
  --{ 3  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_3 union all }
  --{ 4  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_4 union all }
  --{ 5  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_5 union all }
  --{ 7  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_7 union all }
  --{ 8  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_8 union all }
  --{ 9  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_9 union all }
  --{ 101  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_101 union all }
  --{ 102  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_102 union all }
  --{ 108  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_108 union all }
  --{ 109  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_109 union all }
  --{ 110  IN (@list_of_analysis_ids)}?{
  select cohort_definition_id, analysis_id, cast(stratum_1 as varchar), cast(stratum_2 as varchar), 
  cast(stratum_3 as varchar), cast(stratum_4 as varchar), count_value
  from  #results_110 union all }
  select -1, -1, '', '', '', '', -1;

```
If I remove the 110 analysis conditional from the query, the 'FROM DUAL' is removed. However, if I copy/paste the 109 analysis so that it appears twice, the 'FROM DUAL' re-appears so I don't suspect it has anything to do with the contents of the 110 analysis query. 

Tagging @schuemie, @chen-regen and @chrisknoll for awareness

**Comment by chrisknoll** [comment]
This might be a simpler test case to reproduce:

```
query <- "
select -1, -1, '', '', '', '', -1
UNION ALL
select -1, -1, '', '', '', '', -1
;
";

translateSql(renderSql(query, list_of_analysis_ids = c(0:1))$sql,targetDialect = "oracle")$sql
# Returns string with only a FROM DUAL inside the first select.
```

**Comment by schuemie** [comment]
I just committed [changes](https://github.com/OHDSI/SqlRender/commit/088b35d6182bedf4772131553c676c074661e604) that should fix this problem. Could you try it out?

**Comment by chen-regen** [comment]
I tested with cohort generation. Looks like multiple "from dual" is gone. But there are other problems. For example:
```
 CREATE TABLE zztk0hejqualified_events
 
AS
WITH primary_events (event_id, person_id, start_date, end_date, op_start_date, op_end_date, visit_occurrence_id)  AS (SELECT row_number() over (PARTITION BY P.person_id order by P.start_date) as event_id, P.person_id, P.start_date, P.end_date, OP.observation_period_start_date as op_start_date, OP.observation_period_end_date as op_end_date, P.visit_occurrence_id
FROM
(SELECT P.person_id, P.start_date, P.end_date, row_number() OVER (PARTITION BY person_id ORDER BY start_date ASC) ordinal, P.visit_occurrence_id
  FROM 
  (SELECT C.person_id, C.observation_id as event_id, C.observation_date as start_date, (C.observation_date + NUMTODSINTERVAL(1, 'day')) as END_DATE, C.observation_concept_id as TARGET_CONCEPT_ID, C.visit_occurrence_id
from 
(SELECT o.*, row_number() over (PARTITION BY o.person_id ORDER BY o.observation_date, o.observation_id) as ordinal
  FROM OMOPV5_DE.OBSERVATION o

 FROM DUAL) C

 FROM DUAL WHERE (C.observation_date >= TO_DATE(TO_CHAR(2014,'0000')||'-'||TO_CHAR(11,'00')||'-'||TO_CHAR(01,'00'), 'YYYY-MM-DD') and C.observation_date <= TO_DATE(TO_CHAR(2014,'0000')||'-'||TO_CHAR(12,'00')||'-'||TO_CHAR(31,'00'), 'YYYY-MM-DD'))
AND C.observation_type_concept_id in (38000282)
-- End Observation Criteria
   FROM DUAL) P
 FROM DUAL) P
JOIN OMOPV5_DE.observation_period OP on P.person_id = OP.person_id and P.start_date >=  OP.observation_period_start_date and P.start_date <= op.observation_period_end_date
 FROM DUAL WHERE (OP.OBSERVATION_PERIOD_START_DATE + NUMTODSINTERVAL(0, 'day')) <= P.START_DATE AND (P.START_DATE + NUMTODSINTERVAL(0, 'day')) <= OP.OBSERVATION_PERIOD_END_DATE AND P.ordinal = 1
-- End Primary Events

 FROM DUAL)
 SELECT
event_id, person_id, start_date, end_date, op_start_date, op_end_date, visit_occurrence_id

FROM
(SELECT pe.event_id, pe.person_id, pe.start_date, pe.end_date, pe.op_start_date, pe.op_end_date, row_number() over (partition by pe.person_id order by pe.start_date ASC) as ordinal, pe.visit_occurrence_id
  FROM primary_events pe
  
 FROM DUAL) QE

 ;

```
There's wrong "from dual" after "FROM OMOPV5_DE.OBSERVATION o". The extra "from dual" happens in various places in runHeraclesAnalyses.sql.

**Comment by anthonysena** [comment]
Thanks @schuemie - I just tried the new version of SqlRender but am still facing the same issue when using the INSERT statement I posted. And to confirm, I ran sessionInfo() and confirmed I'm using SqlRender_1.4.8.  Are you able to render the INSERT statement properly with your new build or is it just me?

**Comment by chen-regen** [comment]
@anthonysena Anthony, I tested with SqlRender 1.4.8-SNAPSHOT which is the master branch (I have SqlRender checked out on my local).

**Comment by schuemie** [comment]
Ok, I have been puzzling with this a lot. I think I now have everything working in [this commit](https://github.com/OHDSI/SqlRender/commit/9b3119a89348f673aebc0233afbd04e1c6684c72). Could you give it a try?

**Comment by chrisknoll** [comment]
This test passes:

```
query <- "
select -1, -1, '', '', '', '', -1
FROM ( select a, b,c from someTable) D
UNION ALL
select -1, -1, '', '', '', '', -1
UNION ALL
select -1, -1, '', '', '', '', -1
FROM MyTable
;
";

translateSql(renderSql(query, list_of_analysis_ids = c(0:1))$sql,targetDialect = "oracle")$sql
```
this is a case as a subquery, a select without from and a straight select from a table concat'd by UNION ALL. The FROM DUAL only appears in the select without the FROM clause.  So the fix looks good for this case.

@schuemie : I'm wondering if there's a non-pattern replace solution for this 'FROM DUAL" oracle-ism.  I'm not sure if the latest pattern matching is elegant or not, but It feels like it depends on a series of replacement patterns that when applied int he right order, the FROM DUALs are applied correctly.  Is it possible that maybe there is a more java-programatic approach that after the sql is translated, oracle has the additional step of locating anywhere there's a SELECT without a FROM , it injects the FROM DUAL to the query?  I suggest a java-programatic approach becuase you might have more regex flexiblity and parsing logic capability within a java-context vs. relying on pattern-matching and order of replacement.  Just my 2 cents!  You do appear to have it working, so no complaints there!

-Chris

**Comment by anthonysena** [comment]
Thanks @schuemie - this fixed it! We are doing some additional tests to verify but my query above now renders/translates properly. Thanks!

**Comment by schuemie** [comment]
@chrisknoll : yes, you're right that at one point I may need to throw in the towel and reprogram this logic in Java instead of trying to squeeze everything in these rules. The BigQuery translation already uses [some complicated logic that in no way can be expressed in SqlRender's rule logic](https://github.com/OHDSI/SqlRender/blob/master/java/org/ohdsi/sql/BigQueryTranslate.java). 

But for now its working, so maybe when the next issue pops up ;-)

**Comment by chrisknoll** [comment]
No problem, thanks for taking the time. Maybe I can take a stab at it based on how the logic works for big query.
